"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
export type Locale="ru"|"en"|"de"|"uk";
const messages:Record<Locale,Record<string,string>>={
ru:{search:"Книга, автор или дизайнер…",add:"Добавить обложку",login:"Войти",logout:"Выйти",tagline:"Место для сильных обложек",hero1:"Судят по обложке.",hero2:"И это прекрасно.",intro:"Публикуйте дизайн, собирайте честные оценки и находите визуальные идеи для следующей книги.",new:"Новые",popular:"Популярные",best:"Лучшие",low:"С низкой оценкой",notFound:"Ничего не найдено",ratings:"оценок",newWork:"Новая работа",addCover:"Добавить обложку",drop:"Перетащите изображение",title:"Название книги",author:"Автор",description:"Описание",publish:"Опубликовать",back:"Назад",editor:"Выбор редакции",yourRating:"Ваша оценка",chooseRating:"Выберите оценку от 1 до 10",comments:"Комментарии",commentPlaceholder:"Что вы думаете об этой обложке?",createAccount:"Создать аккаунт",nameHint:"Введите имя, которое увидят другие пользователи.",yourName:"Ваше имя",email:"Email",password:"Пароль",register:"Зарегистрироваться",haveAccount:"Уже есть аккаунт?",welcome:"С возвращением",noAccount:"Нет аккаунта?",accountSettings:"Настройки аккаунта",profile:"Профиль",saveProfile:"Сохранить профиль",saved:"Имя сохранено"},
en:{search:"Book, author or designer…",add:"Add cover",login:"Sign in",logout:"Sign out",tagline:"A place for remarkable covers",hero1:"Judge a book by its cover.",hero2:"That’s the point.",intro:"Publish your designs, collect honest ratings and discover visual ideas for the next book.",new:"Newest",popular:"Popular",best:"Top rated",low:"Lowest rated",notFound:"Nothing found",ratings:"ratings",newWork:"New work",addCover:"Add a cover",drop:"Drop an image here",title:"Book title",author:"Author",description:"Description",publish:"Publish",back:"Back",editor:"Editor’s choice",yourRating:"Your rating",chooseRating:"Choose a rating from 1 to 10",comments:"Comments",commentPlaceholder:"What do you think about this cover?",createAccount:"Create account",nameHint:"Enter the name other users will see.",yourName:"Your name",email:"Email",password:"Password",register:"Create account",haveAccount:"Already have an account?",welcome:"Welcome back",noAccount:"No account yet?",accountSettings:"Account settings",profile:"Profile",saveProfile:"Save profile",saved:"Name saved"},
de:{search:"Buch, Autor oder Designer…",add:"Cover hinzufügen",login:"Anmelden",logout:"Abmelden",tagline:"Ein Ort für starke Buchcover",hero1:"Man urteilt nach dem Cover.",hero2:"Und das ist gut so.",intro:"Veröffentliche Designs, sammle ehrliche Bewertungen und entdecke Ideen für das nächste Buch.",new:"Neu",popular:"Beliebt",best:"Bestbewertet",low:"Niedrig bewertet",notFound:"Nichts gefunden",ratings:"Bewertungen",newWork:"Neue Arbeit",addCover:"Cover hinzufügen",drop:"Bild hier ablegen",title:"Buchtitel",author:"Autor",description:"Beschreibung",publish:"Veröffentlichen",back:"Zurück",editor:"Empfehlung",yourRating:"Deine Bewertung",chooseRating:"Bewertung von 1 bis 10 wählen",comments:"Kommentare",commentPlaceholder:"Was hältst du von diesem Cover?",createAccount:"Konto erstellen",nameHint:"Gib den Namen ein, den andere sehen sollen.",yourName:"Dein Name",email:"E-Mail",password:"Passwort",register:"Registrieren",haveAccount:"Schon registriert?",welcome:"Willkommen zurück",noAccount:"Noch kein Konto?",accountSettings:"Kontoeinstellungen",profile:"Profil",saveProfile:"Profil speichern",saved:"Name gespeichert"},
uk:{search:"Книга, автор або дизайнер…",add:"Додати обкладинку",login:"Увійти",logout:"Вийти",tagline:"Місце для сильних обкладинок",hero1:"Судять за обкладинкою.",hero2:"І це прекрасно.",intro:"Публікуйте дизайн, отримуйте чесні оцінки та знаходьте візуальні ідеї для наступної книги.",new:"Нові",popular:"Популярні",best:"Найкращі",low:"З низькою оцінкою",notFound:"Нічого не знайдено",ratings:"оцінок",newWork:"Нова робота",addCover:"Додати обкладинку",drop:"Перетягніть зображення",title:"Назва книги",author:"Автор",description:"Опис",publish:"Опублікувати",back:"Назад",editor:"Вибір редакції",yourRating:"Ваша оцінка",chooseRating:"Оберіть оцінку від 1 до 10",comments:"Коментарі",commentPlaceholder:"Що ви думаєте про цю обкладинку?",createAccount:"Створити акаунт",nameHint:"Введіть ім’я, яке бачитимуть інші користувачі.",yourName:"Ваше ім’я",email:"Email",password:"Пароль",register:"Зареєструватися",haveAccount:"Вже маєте акаунт?",welcome:"З поверненням",noAccount:"Ще немає акаунта?",accountSettings:"Налаштування акаунта",profile:"Профіль",saveProfile:"Зберегти профіль",saved:"Ім’я збережено"}}
const C=createContext({locale:"ru" as Locale,setLocale:(_l:Locale)=>{},t:(key:string)=>key});
export function I18nProvider({children}:{children:React.ReactNode}){const[locale,setLocaleState]=useState<Locale>("ru");useEffect(()=>{const saved=localStorage.getItem("coverly_locale") as Locale|null;if(saved&&messages[saved])setLocaleState(saved)},[]);const setLocale=(next:Locale)=>{setLocaleState(next);localStorage.setItem("coverly_locale",next);document.documentElement.lang=next};const value=useMemo(()=>({locale,setLocale,t:(key:string)=>messages[locale][key]||messages.ru[key]||key}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
